# site settings
title: Tom Callister
subtitle: by HTML5 UP
email: thomas.a.callister@gmail.com
description: I'm a Schmidt AI in Science Fellow in the University of Chicago's Kavli Institute for Cosmological Physics. I enjoy thinking about the detection, analysis, and astrophysics of gravitational waves.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Tom Callister
street_address: The University of Chicago 
street_address_2: 5640 S. Ellis Ave.
city: Chicago
state: IL
zip_code: 60637
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tcallister
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
